["protostar.config"]
protostar_version = "0.6.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
FixedPointMathLib = ["contracts/bonding_curves/FixedPointMathLib.cairo"]
CurveErrorCodes = ["contracts/bonding_curves/CurveErrorCodes.cairo"]
ExponentialCurve = ["contracts/bonding_curves/ExponentialCurve.cairo"]
LinearCurve = ["contracts/bonding_curves/LinearCurve.cairo"]
XykCurve = ["contracts/bonding_curves/XykCurve.cairo"]

NFTPair = ["contracts/NFTPair.cairo"]
NFTPairEnumerable = ["contracts/NFTPairEnumerable.cairo"]
NFTPairERC20 = ["contracts/NFTPairERC20.cairo"]
NFTPairFactory = ["contracts/NFTPairFactory.cairo"]
NFTPairMissingEnumerable = ["contracts/NFTPairMissingEnumerable.cairo"]
Account = ["contracts/tests/Account.cairo"]
ERC20 = ["contracts/tests/ERC20.cairo"]
ERC1155Holder = ["contracts/libraries/ERC1155Holder.cairo"]
ERC1155Receiver = ["contracts/libraries/ERC1155Receiver.cairo"]
felt_uint = ["contracts/libraries/felt_uint.cairo"]
Ownable = ["contracts/openzeppelin/Ownable.cairo"]
ReentrancyGuard = ["contracts/openzeppelin/ReentrancyGuard.cairo"]
storage_contract = ["contracts/tests/storage_contract.cairo"]
